### ISSUE TITLE
Reads like presenter directions

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#4]
https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#the-orchestrate-hub
This section reads like directions to a presenter.

2. Expand Pipelines and select 1 Master Pipeline (1). Point out the Activities (2) that can be added to the pipeline, and show the pipeline canvas (3) on the right.

also this section, should have direction to open or click on something:
Show each of the management categories grouped under Analytics pools, External connections, Orchestration, and Security.

**Comment by ctesta-oneillmsft** [comment]
That is by design, as the intention of this content is to be used by presenter to perform demos. These steps will be repurposed for use on Learn and Instructor led training.

Module 1 is a show and tell module, hence why there is no real direction to open something. We only have 30 minutes so this is by design
